# Generated by Django 2.0b1 on 2017-10-18 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vintage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DateField(verbose_name='year produced')),
                ('rating', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='vintage',
            name='wine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.Wine'),
        ),
    ]
