# Generated by Django 2.0b1 on 2017-10-22 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vintage',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
